### ISSUE TITLE
RedirectSlashes doesn't recognize and skips the prefix pattern in mux#Route scope.

### ISSUE THREAD

**Issue by 0xbkt** [go-chi/chi#340] opened 2018-08-11 19:52 UTC
##### Code:
```go
func main() {
	mux := chi.NewMux()

	mux.Route("/api", func(r chi.Router) {
		r.Use(middleware.RedirectSlashes)

		r.Get("/generate", func(w http.ResponseWriter, r *http.Request) {
			w.Write([]byte("/"))
		})
	})

	. . . .
	. . .
	. .
}
```
##### Problem:
I was expecting to get redirected to `/api/generate` when I hit `/api/generate/` but instead it redirected me to `/generate`. Handler simply ignored the `RoutePattern` of route.

Also, Context#RoutePattern is hard-coded to only replace `/*/`s. Not `/*`s. I also fixed it.

##### Fix:
https://github.com/illenial/chi/tree/redirectslashes-mw-fix-and-context-improvement (current tests passed)

Perhaps, using URL.Path fits for both registered and unregistered routes but I'm not clear.

/cc @VojtechVitek

**Comment by pkieltyka** [comment] 2019-01-08 20:03
I tested this and was unable to reproduce any bugs, closing for now. I've added extra test case for this in v4 as well

**Closed by pkieltyka** 2019-01-08 20:03 UTC
