### ISSUE TITLE
NewWrapResponseWriter: http.Hijacker not wrapped in flushWriter

### ISSUE THREAD

**Issue by nsemikov** [go-chi/chi#544] opened 2020-10-07 14:00 UTC
In my code, gorilla Websocket upgrader fails after NewWrapResponseWriter: https://github.com/go-chi/chi/blob/cf97bef8b1405c9177bd88eca166ed4f16b9fc80/middleware/wrap_writer.go#L15-L36
It print to stdout:
```websocket: response does not implement http.Hijacker```

Seems it happens because there no `Hijack` method in `flushWriter`.

Sorry for my English =)

**Comment by VojtechVitek** [comment] 2020-10-07 15:22
Looks like a duplicate of #543. Closing. Please feel free to reopen.

**Closed by VojtechVitek** 2020-10-07 15:22 UTC

**Comment by titpetric** [comment] 2020-10-09 18:13
@nsemikov are you using Elastic APM or something else that would wrap the http ResponseWriter?

**Comment by nsemikov** [comment] 2020-10-12 07:36
I am using [gqlgen](https://github.com/99designs/gqlgen).

**Comment by titpetric** [comment] 2020-10-12 15:18
It’s likely gqlgen doesn’t implement os.ReaderFrom on their ResponseWriter
wrap. I’d suggest you file the issue upstream too.
