### ISSUE TITLE
Routes nested arbitrarily deep or matching slashes

### ISSUE THREAD

**Issue by hahanein** [go-chi/chi#243] opened 2017-08-11 13:19 UTC
I'm wondering whether there's a standard story for solving the following problem.

I have a route like this:

```golang
r.Get("/{someparameter}/genre/{genre}", handler)
```

And that's fine, except a genre here is a rose tree data structure that can have any number of subgenres and any subgenre can have any number of subgenres and so on and so forth. So in Gorilla I had to resort to match slashes like so:

```golang
r.HandleFunc("/{someparameter}/genre/{genre:[a-z/]*}", handler).Methods("GET") // or something
```

Then I split that into a slice and used it as a path.

Now, I take it, this doesn't work in chi, because the next slash is interpreted as a hard delimiter and no route is found for anything that follows.

Is there a standard story for this and if not, should an API be implemented or is that not within the scope of a REST API router?

Maybe this isn't a feature but a bug?

**Comment by pkieltyka** [comment] 2017-08-11 13:30
Im not familiar with how Gorilla's semantics work. Can you some a psuedo code for the `handler` ? 

why isn't `r.Get("/{someparameter}/genre/{genre}", GenreHandler)` sufficient? perhaps you also need the route `r.Get("/{someparameter}/genre", IndexGenreHandler)` in addition?

**Comment by hahanein** [comment] 2017-08-11 13:41
Maybe I'm doing something wrong but these would be possible GET requests:

```
localhost/en/genre/subgenre
localhost/en/genre/subgenre/subgenre
localhost/fr/genre/subgenre/subgenre/subgenre
etc. pp.
```

As far as I understand it `r.Get("/{someparameter}/genre/{genre}", GenreHandler)` matches only the first example.

Here's some pseudocode for the handler:

```golang
func GenreHandler(w http.ResponseWriter, r *http.Request) {
        languageCode := chi.URLParam(r, "someparameter"))


        path := strings.Split(chi.URLParam(r, "genre"), "/")

        var genres GenreRoseTree = GetGenreRosetree(languageCode)

        var genre GenreRoseTree = genres.TraversePath(path)

        if err := Templates.ExecuteTemplate(w, "genre", genre); err != nil {
                panic(err.Error())
        }
}
```

**Comment by KenjiTakahashi** [comment] 2018-01-05 05:27
Any updates on this? I am making a service that kinda mimicks the S3 API. So I'd like to have URLs in form of `/{bucket}/{key}?args`, where `key` can have slashes in it. I am currently using your asterisk workaround and it works (thanks!), but feels a bit clumsy.

**Comment by VojtechVitek** [comment] 2018-01-05 17:22
@KenjiTakahashi I suggest parsing any slashes in a handler.

ie. route `/{bucket}/*` to a handler.. and parse the `{key}` inside of the handler function

**Comment by KenjiTakahashi** [comment] 2018-01-05 23:28
Yeah, like I wrote, this is what I'm doing right now. But it would be nice to have this better supported.

**Comment by pkieltyka** [comment] 2018-01-06 01:54
@KenjiTakahashi feel free to submit a PR too

**Comment by VojtechVitek** [comment] 2018-01-08 17:54
Slashes are the main separator character in REST APIs. By design.

Matching `multiple/path/parts` into a single variable is an anti-pattern, and I don't think we should ever support it as a first class feature, since chi is meant to be as simple REST router as possible (`chi: lightweight, idiomatic and composable router for building Go HTTP services`).

I think we should close this issue, unless someone comes up with a super simple and clean solution. But in my opinion, `r.Handle("/{bucket}/*", handleMultipleSlashesHandler)` is the only solution we can really come up with. Maybe we can document it better in the README.md?

**Closed** 2020-01-11 01:27 UTC
