### ISSUE TITLE
Wildcard "*" behaves unexpectedly when used in conjunction with a nested router which has url parameters.

### ISSUE THREAD

**Issue by NonLogicalDev** [go-chi/chi#550] opened 2020-11-13 23:10 UTC
Given:
```
	r := chi.NewRouter()

	r.Get("/bare/{param}", testStar)
	r.Get("/bare/{param}/*", testStar)

	r.Route("/case0", func(r chi.Router) {
		r.Get("/{param}", testStar) // (1)
		r.Get("/{param}/*", testStar) // (2)
	})
```
In case `(1)` wildcard `"*"` evaluates to `browse/<path_segment>` given url `<path>/browse/<path_segment>`
In case `(2)` wildcard `"*"` evaluates to `<sub_path_1>/<sub_path_2>` given url `<path>/browse/<path_segment>/<sub_path_1>/<sub_path_2>`

# UPDATE: (Minimum reproducible example)
```go
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/go-chi/chi"
)

func main() {
	r := chi.NewRouter()

	r.Get("/bare/{param}", testStar)
	r.Get("/bare/{param}/*", testStar)

	{ // case 0: Mounting a router using callback.
		r.Route("/case0", func(r chi.Router) {
			r.Get("/{param}", testStar)
			r.Get("/{param}/*", testStar)
		})
	}
	{ // case 1: Explicitly mounting a router.
		sr := chi.NewRouter()
		sr.Get("/{param}", testStar)
		sr.Get("/{param}/*", testStar)
		r.Mount("/case1", sr)
	}

	go http.ListenAndServe(":8080", r)

	testCases := []struct {
		url    string
		params map[string]string
	}{
		{url: "value", params: map[string]string{
			"param": "value",
			"*":     "",
		}},
		{url: "value/sub/path", params: map[string]string{
			"param": "value",
			"*":     "sub/path",
		}},
	}

	prefixes := []string{
		"bare",
		"case0",
		"case1",
	}

	for _, prefix := range prefixes {
		for _, tc := range testCases {
			url := fmt.Sprintf("http://localhost:8080/%v/%v", prefix, tc.url)
			printHttp(url, tc.params)
		}
	}
}

func testStar(rw http.ResponseWriter, r *http.Request) {
	ctx := chi.RouteContext(r.Context())
	fmt.Fprintf(rw, "pattern: %v\n", ctx.RoutePattern())
	fmt.Fprintf(rw, "  param: (%v) *: (%v)", ctx.URLParam("param"), ctx.URLParam("*"))
}

func printHttp(url string, params map[string]string) {
	r, err := http.Get(url)
	if err != nil {
		fmt.Println("url:", url, "\n\terr:", err)
	}
	data, _ := ioutil.ReadAll(r.Body)

	fmt.Println("url:", url)

	fmt.Println("--   ACTUAL:")
	fmt.Println(string(data))

	fmt.Println("-- EXPECTED:")
	fmt.Printf("  param: (%v) *: (%v)", params["param"], params["*"])

	fmt.Printf("\n\n")
}
```
## Output:
```
url: http://localhost:8080/bare/value
--   ACTUAL:
pattern: /bare/{param}
  param: (value) *: ()
-- EXPECTED:
  param: (value) *: ()

url: http://localhost:8080/bare/value/sub/path
--   ACTUAL:
pattern: /bare/{param}/*
  param: (value) *: (sub/path)
-- EXPECTED:
  param: (value) *: (sub/path)

url: http://localhost:8080/case0/value
--   ACTUAL:
pattern: /case0/{param}
  param: (value) *: (value)
-- EXPECTED:
  param: (value) *: ()

url: http://localhost:8080/case0/value/sub/path
--   ACTUAL:
pattern: /case0/{param}/*
  param: (value) *: (sub/path)
-- EXPECTED:
  param: (value) *: (sub/path)

url: http://localhost:8080/case1/value
--   ACTUAL:
pattern: /case1/{param}
  param: (value) *: (value)
-- EXPECTED:
  param: (value) *: ()

url: http://localhost:8080/case1/value/sub/path
--   ACTUAL:
pattern: /case1/{param}/*
  param: (value) *: (sub/path)
-- EXPECTED:
  param: (value) *: (sub/path)
```

**Comment by NonLogicalDev** [comment] 2020-11-13 23:29
So far the best workaround I have is something like this:
```
func chiUrlWildcard(r *http.Request) string {
	rctx := chi.RouteContext(r.Context())
	if strings.HasSuffix(rctx.RoutePattern(), "*") {
		return rctx.URLParam("*")
	}
	return ""
}
```

**Comment by pkieltyka** [comment] 2020-11-24 14:33
hey @NonLogicalDev --

In general, the wildcard pattern in the route must be specified as `*`, and it will capture everything as you'd expect with the "*", and you can retrieve that data with `chi.URLParam(r, "*")`

However, I see you're using mux.Route(), but I'm not sure why you're specifying `nil` as the second argument? I think I should actually panic and warn the user if they pass nil as I don't see a good reason to allow it. The `Route(pattern string, fn func(r Router)) Router` method is use if you want to mount a nested/child mux. If you're passing "nil", then you really shouldn't be using it. 

See: https://github.com/go-chi/chi/blob/master/mux.go#L260-L270 and https://github.com/go-chi/chi/blob/master/mux.go#L272-L317

`Route(..)` is a short-hand / sugar method that calls `Mount(pattern string, handler http.Handler)`, in order for it to join the mux's, it will set a wildcard path on the parent route, which is then picked up by an inline middleware to set the path. In normal usage (when handler is not nil, it works fine). But seems you've caught an edge case here by passing a nil child mux then setting a method on the parent route. I will make a PR to help others avoid this issue.

**Comment by pkieltyka** [comment] 2020-11-24 14:37
Fix in https://github.com/go-chi/chi/pull/552

**Comment by NonLogicalDev** [comment] 2020-11-24 19:42
@pkieltyka My bad, for using this weird pattern, did not realize somehow that it was just a sugar on top of `Mount`.

I coded up an test example, which seems to work as expected now:
```go
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/go-chi/chi"
)

func main() {
	r := chi.NewRouter()

	r.Get("/bare", testStar)
	r.Get("/bare/*", testStar)

	r.Route("/router", func(r chi.Router) {
		r.Get("/", testStar)
		r.Get("/*", testStar)
	})

	sr := r.Route("/strage-concoction", nil)
	sr.Get("/", testStar)
	sr.Get("/*", testStar)

	go http.ListenAndServe(":8080", r)

	printHttp("http://localhost:8080/bare")
	printHttp("http://localhost:8080/bare/sub/path")
	printHttp("http://localhost:8080/router")
	printHttp("http://localhost:8080/router/sub/path")
	printHttp("http://localhost:8080/strage-concoction")
	printHttp("http://localhost:8080/strage-concoction/sub/path")
}

func testStar(rw http.ResponseWriter, r *http.Request) {
	ctx := chi.RouteContext(r.Context())
	fmt.Fprintf(rw, "%v [*: %v]", ctx.RoutePattern(), chi.URLParam(r, "*"))
}

func printHttp(url string) {
	r, err := http.Get(url)
	if err != nil {
		fmt.Println("url:", url, "err:", err)
	}
	data, _ := ioutil.ReadAll(r.Body)
	fmt.Println("url:", url, "resp:", string(data))
}
```
```
url: http://localhost:8080/bare resp: /bare [*: ]
url: http://localhost:8080/bare/sub/path resp: /bare/* [*: sub/path]
url: http://localhost:8080/router resp: /router/ [*: ]
url: http://localhost:8080/router/sub/path resp: /router/* [*: sub/path]
url: http://localhost:8080/strage-concoction resp: /strage-concoction/ [*: ]
url: http://localhost:8080/strage-concoction/sub/path resp: /strage-concoction/* [*: sub/path]
```

**Comment by pkieltyka** [comment] 2020-11-24 19:57
@NonLogicalDev can you update your example against master (now that https://github.com/go-chi/chi/pull/552 is merged) ?

**Comment by pkieltyka** [comment] 2020-11-24 19:59
I believe what you want is..

```go
r := chi.NewRouter()

r.Get("/bare/{param}", testStar)
r.Get("/bare/{param}/*", testStar)

r.Route("/router", func(r chi.Router) {
	r.Get("/{param}", testStar)
	r.Get("/{param}/*", testStar)
})
```

note that this code is equivalent:

```go
r := chi.NewRouter()

r.Get("/bare/{param}", testStar)
r.Get("/bare/{param}/*", testStar)

sr := chi.NewRouter()
r.Get("/{param}", testStar)
r.Get("/{param}/*", testStar)

r.Mount("/router", sr)
```

**Comment by NonLogicalDev** [comment] 2020-11-24 20:12
@pkieltyka I updated the test-cases to print expected values

**Comment by pkieltyka** [comment] 2020-11-24 20:38
@NonLogicalDev as of the fix (on master), you example panics due to the error I mentioned:

```
panic: chi: attempting to Route() a nil subrouter on '/case1'

goroutine 1 [running]:
github.com/go-chi/chi.(*Mux).Route(0xc000134240, 0x71f9a0, 0x6, 0x0, 0x784da0, 0xc0001342a0)
	/home/peter/Dev/go/src/github.com/go-chi/chi/mux.go:265 +0x157
main.main()
	/home/peter/Dev/go/src/github.com/go-chi/chi/_examples/hello-world/main.go:24 +0x12e
exit status 2
```

please make sure to use master now that I force the correct usage

**Comment by NonLogicalDev** [comment] 2020-11-24 20:39
@pkieltyka True, I can take out `case1` but all other cases experience the same problem.

**Comment by pkieltyka** [comment] 2020-11-24 20:55
Okay, I think I found the small edge case... see below

See below..

```go
package main

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi"
)

func main() {
	r := chi.NewRouter()

	r.Get("/bare/{param}", testStar)
	r.Get("/bare/{param}/*", testStar)

	r.Route("/case0", func(r chi.Router) {
		r.Get("/{param}", testStar)
		r.Get("/{param}/*", testStar)
	})

	http.ListenAndServe(":3333", r)
}

func testStar(rw http.ResponseWriter, r *http.Request) {
	ctx := chi.RouteContext(r.Context())

	fmt.Fprintf(rw, "pattern: %v\n", ctx.RoutePattern())
	fmt.Fprintf(rw, "  param: (%v)   *: (%v)", ctx.URLParam("param"), ctx.URLParam("*"))
}
```

run it: `go run .`

**test runs:**

```shell
➜  ~ curl http://localhost:3333/bare/hi
pattern: /bare/{param}
  param: (hi)   *: ()%
```
^-- **expected by design**

```shell
➜  ~ curl http://localhost:3333/bare/hi/wildddddddddd
pattern: /bare/{param}/*
  param: (hi)   *: (wildddddddddd)%   
```
^--- **expected by design**, as the pattern is `/bare/{param}/*`, whereby `/bare/{param}/` will match the "hi" and the `*` will match the "wildddddddd"

```shell
➜  ~ curl http://localhost:3333/case0/hi          
pattern: /case0/{param}
  param: (hi)   *: (hi)%   
```
^--- **bug!** the "*" param should be empty here

```shell
➜  ~ curl http://localhost:3333/case0/hi/yes      
pattern: /case0/{param}/*
  param: (hi)   *: (yes)%    
```
^--- **expected by design**

------

so the edge case here is "*" is setting the same value as the param, which is the parameter from the subrouter

**Comment by NonLogicalDev** [comment] 2020-11-24 20:58
@pkieltyka Yes! that is the underlying issue I was trying to report =] Thank you for being so prompt and working with me on this!

**Comment by NonLogicalDev** [comment] 2020-11-24 21:05
Cleaned up the issue description.

**Comment by pkieltyka** [comment] 2020-11-24 21:20
should be fixed in https://github.com/go-chi/chi/pull/553

lmk

**Closed** 2020-11-25 02:12 UTC
